sudo: required

language: python

notifications:
  email: false

branches:
  only:
  - manual

services:
  - docker

script:
  - docker-compose build
  - docker-compose up

before_deploy:
  - git config --local user.name "USER_NAME"
  - git config --local user.email "USER@EMAIL.COM"
  - git tag "$TRAVIS_COMMIT_MESSAGE"

deploy:
  provider: releases
  api_key: $GHTOKEN
  file:
    - "assets/ants.js/ants.js"
  body: "$TRAVIS_COMMIT_MESSAGE"
  target_commitish: $TRAVIS_COMMIT
  skip_cleanup: true
  on:
    all_branches: true
