sudo: required

language: python

notifications:
  email: false

branches:
  only:
  - master

before_script:
  - pip install rdflib

script:
  - python get_antonyms/get_antonyms.py

deploy:
  provider: releases
  api_key: $GHTOKEN
  file:
    - "assets/ants.js/ants.js"
  body: "$TRAVIS_BRANCH: $TRAVIS_COMMIT_MESSAGE"
  target_commitish: $TRAVIS_COMMIT
  skip_cleanup: true
  on:
    all_branches: true
